apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: qahub-elasticsearch
  namespace: database
spec:
  version: 8.11.1
  auth:
    fileRealm:
    - secretName: elasticsearch-password-secret
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
            - name: READINESS_PROBE_TIMEOUT
              value: "60"
          resources:
            requests:
              memory: 2Gi
              cpu: "250m"
            limits:
              memory: 2Gi
              cpu: "1000m"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
  http:
    tls:
      selfSignedCertificate:
        disabled: true