apiVersion: viaduct.ai/v1
kind: ksops 
metadata:
  name: notification-service-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./notification-service/secret.sops.yaml