# apps/base/qa-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-service
  labels:
    app: qa-service
spec:
  selector:
    matchLabels:
      app: qa-service
  template:
    metadata:
      labels:
        app: qa-service
    spec:
      containers:
      - name: qa-service
        image: satiu/qahub-qa-service:latest # This tag will be replaced by overlays
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
          name: grpc
        readinessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
