apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: s13658395102@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          # 如果你的 Ingress Controller 有一个特定的 class name，请在这里指定
          # class: nginx 
          # 对于较新版本的 NGINX Ingress Controller，使用 ingressClassName
          ingressClassName: nginx
