# apps/overlays/dev/search-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config-dev
data:
  # Log config
  LOG_LEVEL: "debug"
  LOG_FORMAT: "json"

  # Kafka config
  KAFKA_BROKERS: "qahub-kafka-kafka-bootstrap.messaging.svc.cluster.local:9092"
  KAFKA_TOPICS_QA_EVENTS: "qa_events_dev"

  # Elasticsearch config
  ELASTICSEARCH_URLS: "http://qahub_user:test123@qahub-elasticsearch-es-http.database.svc.cluster.local:9200"
  ELASTICSEARCH_USERNAME: "qahub_user"
  ELASTICSEARCH_HOST: "qahub-elasticsearch-es-http.database.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  
  # Service-specific config
  SERVICES_SEARCH_SERVICE_GRPC_PORT: "50053"
  SERVICES_SEARCH_SERVICE_HTTP_PORT: "8083"
  SERVICES_SEARCH_SERVICE_PUBLIC_METHODS: "/grpc.health.v1.Health/Check"