#ENC[AES256_GCM,data:fdMudjkeKR0vZTCZ708YcntTGdgpDp6NBOE2Xwv1wQ==,iv:Wd4BAfBBVw+dQg1y7+aWTJQ4FV6v1oUQHiol4CX8Tf0=,tag:PipNPJnHyyFnW2fpWyseIQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:+hA=,iv:SqTwhOsCwpQAk7772C8Vsptq4Uly0YAkiMGkmdtEeNE=,tag:DOLvS2pc4130FPB9zqIVSA==,type:str]
kind: ENC[AES256_GCM,data:mnXdTA1b,iv:eNdrHIGOSpMilGhZM+thz8se2VptH49Wpl2EqnjrPFQ=,tag:x2ONPOdvVGwq/u+cvPg0wg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0eylLFJG4khSlwLyRzX1azN1CJpyAhPA,iv:RYQMN9jfX5JZ3Q6rI1Qa6ZnGKKxmhrtb9pDhkgX66vQ=,tag:gaXWbYEl2CpZurL6W2qWgA==,type:str]
    namespace: ENC[AES256_GCM,data:+8TAmpZ2pDg=,iv:USbZMckMGVfDDnJWFwvkEAJmReCDwUKnlRV9SuxVIwk=,tag:n3X3nLj499ZsGmOFAh4O4A==,type:str]
type: ENC[AES256_GCM,data:ZLZQmKqI,iv:ZNbn8Y3DP/K4ntC438H+5QM1TrEa5hbF4KEogCFduYI=,tag:pf6RW3W8zk/ksHb6n3245w==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:PqiKv2iKTw==,iv:uR6JRjRnp8Emdtvg32B/1fDamxKxe3HDd0VjB87miOU=,tag:nveXzXkvqijvIXrCUXK7Rg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:+NG+w+0jJQ==,iv:3LqbrJw2FlZ7zxG5U/wKFs7O7sSqC5904D9uiLfe6IM=,tag:MUaDaeX+w1K30TCWlAF96g==,type:str]
sops:
    lastmodified: "2025-10-27T15:52:02Z"
    mac: ENC[AES256_GCM,data:OoNPizxnM3a3Hn46wA45FwneNO1Ni+Yqnn3l6Ry6cKyhVnT6EhENsJ8T2mZRTUTLv1FwXpBvyQ7DtzCOmB8hgYgvdfPYsPRRVitnVX1s9+p4MzLrU5EiJGvDUkUvy7i2KhclXOS0OE0yjUMJ0LBAuFTnnXFBJUINamzADqGpM0g=,iv:OvxoieKss4OP9pgOzuDufhmRaOrb6PwVvFZDlkdSdCY=,tag:Iz0OvkKoKH6Qxa746t8OXQ==,type:str]
    pgp:
        - created_at: "2025-10-27T14:48:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw2mPq80x9U3AQ//asWpfnwgsyLyHRGFWYBW9FopXiPv2VH7Q5NQ3+zzTQzg
            xSyPTWmDn6sw00Gxe8tbvWHaExw0Twpji0YnC+ea0v6oeuGZOYIdVfnszv3I3mol
            OM13T8/qP6lUcVu4ZMP3XXHI/oJLre1HWqHkxt0/AqsK7tw7gsSVKXFGSdvG94/8
            sDCsl+R+rANDZ719r9tqigN/9gQRHKD3p+h8zP8X3lc4CJpsSTM+DtgmPHkYXKkJ
            LedEp3QFaP+FC1BJLkm0AB46mIxdRYESvPZtRpDIEv0Fomtsk+Qaz3v9clO6o8wC
            wzSlZpr9TRZQkf2l+NDu3dgWD4DrMApNqmiFiRx8gVAkbce/VjoVLUfGjshzOuuU
            OvTN5HkXr+DGPElo0YbJJa/e90v2JCPlMnoZ3qto6wNi/qvqVwDB9bgHeZV2ZLSC
            Ek8Vp5256FGVthdJyNZrjCs6Ywr67TI8xFzJifBfrMRtMU2In2t4FF6FtOj68TrY
            RU+uHXVNUJa9n2nWT5YxotsL9YxFupkmJT3zOLISBiEmjDXqMYcrz9TPA21xAHjr
            VR8d/W+J4IeLNJ7x78BgtOqBLeaeKZdklOtttZgTvdOl4ubeVt4RrTqzeVh3ZlXf
            NO8WUj1GhCKsORwR56IESaEGar6hGq+oVYQWYwCC/q6JFQBJoIYV30xXt252rn/S
            XgEow/QC3qZoGH86OB4VTmTiYzPkjygiwCDwMYG0duXlc8CmgHFS2wscDapEGusv
            1OWWke0LFr2XEtOQhg5E3VNaxb6Jq5qCTwUsemIcFvwi0i3uYpQNRnboSUT8hUQ=
            =qmq+
            -----END PGP MESSAGE-----
          fp: C5877EAFB9F2B819B4F9D98D8BE1E4F3EE2D2F7B
    unencrypted_suffix: _unencrypted
    version: 3.11.0
