# apps/base/search-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: satiu/qahub-search-service:latest # This tag will be replaced by overlays
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50053
          name: grpc
        readinessProbe:
          grpc:
            port: 50053
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50053
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false